travis:
  secure:
    BINSTAR_TOKEN: Brxb/f4TolAcEf2vZ/wR3vxISIC+aBgI73mTDD9gDyOP1sDFJApJeh8LTK3zvKN3I0v0nXBau4S6svbdFxwD0KaZhSrjVDT+WrEzfPbfWXNCavl/cqLuFarXXs9WnxErGKh4UfvuNpe3WiFWARiTMf+Bq6IfN3O9HKVS+853SCk8YnEfTeX9Kf7uuR6GBBQTbQZS/B5rWvFqLUWadHy5xQ/L0KcVHoJkGdDfmqiS7VRdyXO8UR1YrhrEmPE+uUa+4Ze3y0ldGdM1sJbTQyI6lN6UeGxyukFHT5ld7E8qYBvckXhS2cBbX4fdxjy/XfKboV1Ax/WVjyXJT2dmCwZwdvFQEv7+7amDbhrHj8JHkJC4PIkH1P2hcUrIow0TW7RYcad2rBNd6p8FSE14+5wUPZL33WWRXvXTUaxkcNjYlGHOFWOm2RO63Tc0cXB2kToKCqTCDnHg7P7MVvypY0/Kplx5ME03D7EO+Mr8hqn2HSOhXeMd9bBttB3He5AhA0mcOxbhWPX73fYoNMUkkkATr8oLYGgwvOH8d3XqQk1Roe2Tkz3zRJy03ibFO08nINO4Gd51eyn+qgkammmlSsL2HhvkUYfUS6ntd9oR8U6ntPQtc2VhKfjDCxwyBOlIUUOyQtY1PudRzlw79mRbQKJnNOwXuAw+ie+jD5NK5TiNYu8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
